package:
  name: powershell-extension-test
  version: 0.1.0

build:
  number: 0
  script: build.ps1 # Should auto-detect powershell interpreter

requirements:
  build:
    - powershell

about:
  summary: Test auto-detection of powershell interpreter from .ps1 extension
  license: MIT
