context:
  integer: ${{ xinteger }}
  float: ${{ xfloat }}
  string: ${{ xstring }}
  boolean: ${{ xboolean }}
  cinteger: 5
  cfloat: 1.23
  cstring: "blah"
  cboolean: true
  cquoted_bool: "true"
  cquoted: "5"
  list:
    - a
    - b
    - c
  inline_list: [a, b, c]
  is_integer: ${{ xinteger is integer }}
  is_float: ${{ xfloat is float }}
  is_string: ${{ xstring is string }}
  is_boolean: ${{ xboolean is boolean }}
  is_cinteger: ${{ cinteger is integer }}
  is_cfloat: ${{ cfloat is float }}
  is_cstring: ${{ cstring is string }}
  is_cboolean: ${{ cboolean is boolean }}
  is_cquoted: ${{ cquoted is string }}
  is_list: ${{ list is sequence }}
  is_inline_list: ${{ inline_list is sequence }}
  is_list_elem: ${{ list[0] is string }}
  computed_int: ${{ "12.3" | replace(".", "") | int }}
  is_computed_int: ${{ computed_int is integer }}
  is_quoted_true: ${{ cquoted_bool is string }}
  # quoted bool is quoted in variants.yaml and thus should be a string
  is_quoted_true_var: ${{ quoted_bool is string }}
  is_quoted_int_var: ${{ quoted_int is string }}
  starting_with: ${{ xstring is startingwith('blah') }}
  not_starting_with: ${{ xstring is startingwith('foo') }}
  ending_with: ${{ xstring is startingwith('blah') }}
  not_ending_with: ${{ xstring is startingwith('foo') }}

package:
  name: testtypes
  version: "1.2.3"
