package:
  name: run_exports_test
  version: "1.0.0"

requirements:
  host:
    - zlib
  run_exports:
    - ${{ pin_subpackage("run_exports_test", exact=True) }}

  # avoid adding libzlib
  ignore_run_exports:
    by_name:
      - libzlib
