

package:
  name: run_exports_test
  version: "1.0.0"

build:
  merge_build_and_host_envs: true

requirements:
  build:
    - zlib
  run_exports:
    - ${{ pin_subpackage("run_exports_test", exact=True) }}
  # avoid from package
  ignore_run_exports:
    from_package:
      - zlib
