import json
import shutil
from pathlib import Path
from subprocess import STDOUT

import yaml

from helpers import RattlerBuild, get_extracted_package, get_package


def test_build_steps(rattler_build: RattlerBuild, recipes: Path, tmp_path: Path):
    """`build.steps` compiles into the generated wrapper and runs in order.

    Run steps execute as scoped sections: one writes via the build-time
    `$PREFIX`, one uses step-local `env`, one proves env does not leak, and one
    runs from a step-local `cwd`.
    """
    rattler_build.build(
        recipes / "build_steps", tmp_path, extra_args=["--experimental"]
    )
    pkg = get_extracted_package(tmp_path, "build_steps_test")

    step1 = pkg / "share" / "build_steps" / "step1.txt"
    step2 = pkg / "share" / "build_steps" / "step2.txt"
    step3 = pkg / "share" / "build_steps" / "step3.txt"
    cwd_pwd = pkg / "share" / "build_steps" / "cwd" / "pwd.txt"

    assert step1.exists(), "first step did not run"
    assert step2.exists(), "second step did not run"
    assert step3.exists(), "third step did not run"
    assert cwd_pwd.exists(), "cwd step did not run in its target directory"
    assert "hello-from-step" in step2.read_text(), (
        "step-local env did not reach the section"
    )
    assert "unset" in step3.read_text(), "step-local env leaked to a later section"


def test_metadata_step_runs_before_solving_and_defines_build_plan(
    rattler_build: RattlerBuild, recipes: Path, tmp_path: Path
):
    """Metadata bootstrap output participates in solving and build execution."""
    rattler_build.build(
        recipes / "metadata_step", tmp_path, extra_args=["--experimental"]
    )
    pkg = get_extracted_package(tmp_path, "metadata-step-example")

    assert (
        pkg / "share" / "metadata-step-example" / "generated.txt"
    ).read_text() == "generated by metadata step\n"
    rendered = yaml.safe_load(
        (pkg / "info" / "recipe" / "rendered_recipe.yaml").read_text()
    )["recipe"]
    assert rendered["requirements"]["build"] == ["python"]
    assert rendered["requirements"]["host"] == ["zlib"]
    assert rendered["build"]["steps"][0]["name"] == "install"


def test_python_metadata_backend_builds_external_rich_source(
    rattler_build: RattlerBuild, recipes: Path, tmp_path: Path
):
    """One provider package supplies both pyproject metadata and wheel steps."""
    provider_output = tmp_path / "provider-output"
    channel = tmp_path / "channel"
    consumer_output = tmp_path / "consumer-output"
    rattler_build.build(recipes / "metadata_python_provider", provider_output)
    provider = get_package(provider_output, "python-rattler-build-steps")
    rattler_build("publish", str(provider), "--to", str(channel))
    build_args = rattler_build.build_args(
        recipes / "metadata_python_backend",
        consumer_output,
        custom_channels=[channel.as_uri(), "conda-forge"],
        extra_args=["--experimental"],
    )
    build_output = rattler_build(*build_args, stderr=STDOUT)
    assert "Generated recipe after build.metadata:" in build_output
    assert "- uses: python:build@==0.1.0" in build_output
    assert "summary: Render rich text" in build_output
    assert "Ignoring prefix-detection" not in build_output
    pkg = get_extracted_package(consumer_output, "rich")

    index = json.loads((pkg / "info" / "index.json").read_text())
    assert index["noarch"] == "python"
    assert "python >=3.8.0" in index["depends"]
    assert "markdown-it-py >=2.2.0" in index["depends"]
    assert "pygments >=2.13.0,<3" in index["depends"]
    about = json.loads((pkg / "info" / "about.json").read_text())
    assert about["license"] == "MIT"
    assert about["summary"].startswith("Render rich text")
    rendered = yaml.safe_load(
        (pkg / "info" / "recipe" / "rendered_recipe.yaml").read_text()
    )["recipe"]
    assert rendered["requirements"]["host"] == [
        "python",
        "pip",
        "python-build",
        "poetry-core >=1.0.0",
    ]
    assert rendered["build"]["steps"][0]["uses"] == "python:build@==0.1.0"
    assert (pkg / "site-packages" / "rich" / "__init__.py").exists()
    assert (pkg / "info" / "licenses" / "LICENSE").exists()


def test_reusable_steps_inputs_and_generated_licenses(
    rattler_build: RattlerBuild, recipes: Path, tmp_path: Path
):
    """Reusable inputs render before solving and generated licenses are metadata-only."""
    rattler_build.build(
        recipes / "reusable_steps", tmp_path, extra_args=["--experimental"]
    )
    pkg = get_extracted_package(tmp_path, "reusable_steps_test")

    assert (pkg / "share" / "reusable-steps" / "marker.txt").exists()
    license_file = pkg / "info" / "licenses" / "dependency.txt"
    assert license_file.read_text().strip() == "dependency-license"
    assert not (pkg / "generated-licenses").exists()

    index = json.loads((pkg / "info" / "index.json").read_text())
    assert "zlib" in index["depends"]
    run_exports = json.loads((pkg / "info" / "run_exports.json").read_text())
    assert run_exports["strong"] == ["reusable-abi"]
    about = json.loads((pkg / "info" / "about.json").read_text())
    assert about["dev_url"] == "https://example.com/reusable-step"


def test_packaged_step_provider_uses_standalone_environment(
    rattler_build: RattlerBuild, recipes: Path, tmp_path: Path
):
    """A versioned provider resolves from a local channel without entering the package."""
    provider_output = tmp_path / "provider-output"
    channel = tmp_path / "channel"
    consumer_output = tmp_path / "consumer-output"
    rattler_build.build(recipes / "step_provider", provider_output)
    provider_package = get_package(provider_output, "test-rattler-build-steps")
    rattler_build("publish", str(provider_package), "--to", str(channel))

    rattler_build.build(
        recipes / "step_provider_consumer",
        consumer_output,
        custom_channels=[channel.as_uri(), "conda-forge"],
        extra_args=["--experimental"],
    )
    pkg = get_extracted_package(consumer_output, "step-provider-consumer")
    assert (
        pkg / "share" / "step-provider" / "marker.txt"
    ).read_text().strip() == "exact-provider-worked"
    assert not any(pkg.rglob("test-rattler-build-steps*"))


def test_step_cache_skips_and_invalidates(
    rattler_build: RattlerBuild, recipes: Path, tmp_path: Path
):
    """Step-written input/output conditions skip work until an input changes."""
    project = tmp_path / "project"
    shutil.copytree(recipes / "step_cache", project)
    output = tmp_path / "output"
    args = (
        "run",
        "cached",
        "--recipe",
        str(project),
        "--source-dir",
        str(project),
        "--output-dir",
        str(output),
        "--experimental",
    )

    rattler_build(*args)
    rattler_build(*args)
    assert (project / "run-count.txt").read_text().splitlines() == ["run"]

    (project / "input.txt").write_text("changed\n")
    rattler_build(*args)
    assert (project / "run-count.txt").read_text().splitlines() == ["run", "run"]
    assert (project / "generated.txt").read_text() == "changed\n"


def test_default_build_script_still_runs(
    rattler_build: RattlerBuild, recipes: Path, tmp_path: Path
):
    """A legacy build.sh/build.bat is still discovered when no script is declared."""
    rattler_build.build(recipes / "default_build_script", tmp_path)
    pkg = get_extracted_package(tmp_path, "default_build_script_test")

    marker = pkg / "share" / "default_build_script" / "marker.txt"
    assert marker.exists(), "default build script did not run"
    assert "default-build-script" in marker.read_text()
