schema_version: 1

context:
  version: "12.1.0"
recipe:
  name: pillow-split
  version: ${{ version }}

build:
  number: 0

outputs:
  - package:
      name: pillow
    requirements:
      host:
        - python
      run:
        - python

  - package:
      name: pillow-tests
    requirements:
      run:
        - ${{ pin_subpackage("pillow", exact=True) }}
