# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: toml
  version: 0.10.2

package:
  name: "${{ name|lower }}"
  version: "${{ version }}"

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f

build:
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python 3.12.1
    - pip 23.3.2
    - setuptools 68
  run:
    - python

about:
  homepage: https://github.com/uiri/toml
  license: MIT
  license_file: LICENSE
  summary: Python lib for TOML.
