context:
  use_noarch: false

package:
  name: test-conditional-noarch
  version: 1.0.0

build:
  number: 0
  # When use_noarch is false, this should result in empty/null and use the default (no noarch)
  # When use_noarch is true, this should set noarch to "python"
  noarch: ${{ "python" if use_noarch }}
  script:
    - echo "Building package"

requirements:
  host:
    - python
  run:
    - python
