context:
  name: xtensor
  version: 0.24.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/xtensor-stack/xtensor/archive/${{ version }}.tar.gz
    sha256: f87259b51aabafdd1183947747edfff4cff75d55375334f2e81cee6dc68ef655
  - file_name: test.avi
    url: https://github.com/opencv/opencv_extra/raw/master/testdata/highgui/video/VID00003-20100701-2204.avi
    sha256: 78884f64b564a3b06dc6ee731ed33b60c6d8cd864cea07f21d94ba0f90c7b310

test:
  source_files:
    - test.avi
  files:
    - test-file.txt
    - test-folder/
  commands:
    - echo "test"
    - test -f ./test.avi
    - test -f ./test-file.txt
    - test -d ./test-folder
    - test -f ./test-folder/test-file-2.txt
    - test -f ./test-folder/test-file-3.txt