

package:
  name: "git_source"
  version: "1"

source:
  - git: https://github.com/prefix-dev/rattler-build
    tag: v0.1.0
  - git: https://github.com/wolfv/rattler-build
    branch: main
    target_directory: main
  - git: https://github.com/prefix-dev/rattler-build
    target_directory: HEAD
  - git: https://github.com/prefix-dev/rattler-build
    rev: df83c1edf287a756b8fc995e03e9632af0344777
    target_directory: initial_version
  - git: git@github.com:prefix-dev/rattler-build.git
  # - git: https://github.com/tensorflow/tensorflow
  #   target_directory: tensorflow

build:
  script:
    - test -f README.md
    - cat ./initial_version/build.sh
