package:
  name: test-source-files
  version: "1.0.0"

source:
  - path: ./src

build:
  script:
    - if: unix
      then:
        - mkdir -p $PREFIX/bin
        - echo "hello" > $PREFIX/bin/hello.txt
      else:
        - mkdir %PREFIX%\bin
        - echo hello > %PREFIX%\bin\hello.txt

tests:
  - script:
      - if: unix
        then:
          - test -f ./data.txt
          - cat ./data.txt
        else:
          - if not exist .\data.txt (exit 1)
    files:
      source:
        - ./
