context:
  version: "0.11.9"

package:
  name: cargo-edit
  version: "{{ version }}"

source:
  url: https://github.com/killercup/cargo-edit/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 46670295e2323fc2f826750cdcfb2692fbdbea87122fe530a07c50c8dba1d3d7

build:
  script:
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .

requirements:
  build:
    - "{{ compiler('rust') }}"
    - cargo-bundle-licenses

test:
  commands:
    - cargo-upgrade --help

about:
  home: https://github.com/killercup/cargo-edit
  license: MIT
  description: "A utility for managing cargo dependencies from the command line."
  about: "A utility for managing cargo dependencies from the command line."
