package:
  name: foo
  version: 1.0.0

build:
  script: |
    ! test -f $PREFIX/.github/foo
    mkdir -p $PREFIX/.github/
    echo abc > $PREFIX/.github/foo
    test -f $PREFIX/.github/foo

tests:
  - package_contents:
      files:
        - .github/foo
