package:
  name: build_files
  version: 1.0.0

source:
  - path: ./test-folder
    files:
      include:
        - "*.txt"
      exclude:
        - "exclude*"

build:
  script:
    - echo "running build (test)"
    - test -f included.txt
    - test ! -f not-included
    - test ! -f excluded.txt
