schema_version: 1
package:
  name: test-rattler-build-steps
  version: 1.0.0
build:
  noarch: generic
  script: >-
    python -c "import os,pathlib,shutil; p=pathlib.Path(os.environ['PREFIX'])/'etc/rattler-build/steps/test'; shutil.copytree(pathlib.Path(os.environ['RECIPE_DIR'])/'steps',p)"
requirements:
  build: [python]
  run: [six]
