

package:
  name: ros-humble-turtlebot4-msgs
  version: 1.0.3

source:
  git: https://github.com/ros2-gbp/turtlebot4-release.git
  rev: release/humble/turtlebot4_msgs/1.0.3-1
  target_directory: ros-humble-turtlebot4-msgs/src/work

build:
  script:
    - if: win
      then: bld_ament_cmake.bat
      else: build_ament_cmake.sh
  number: 3
about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ninja
    - setuptools
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then:
        - tapi
    - cmake
    - if: build_platform != target_platform
      then:
        - pkg-config
        - python
        - cross-python_${{ target_platform }}
        - cython
        - numpy
  host:
    - numpy
    - pip
    # TODO: replace with inline-if
    - if: build_platform == target_platform
      then:
        - pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-generators
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.3 humble
  run:
    - python
    - ros-humble-ros-workspace
    - ros-humble-rosidl-default-runtime
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.3 humble
    - if: osx and x86_64
      then:
        - __osx >=${{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
