package:
  name: 7z-source
  version: 0.1.0
source:
  - url: https://downloads.sourceforge.net/project/sevenzip/7-Zip/24.08/7z2408-src.7z
    sha256: 4df7a62e5ce503892f500b1f96f0a954931c5266900c439102040957b25a90c6

build:
  script:
    - if: unix
      then:
        - test -d CPP
      else:
        - if not exist "CPP\" exit 1
