package:
  name: python-abi3-package-sample
  version: 0.0.1

source:
  url: https://github.com/joerick/python-abi3-package-sample/archive/6f74ae7b31e58ef5f8f09b647364854122e61155.tar.gz
  sha256: e81fd4d4c4f5b7bc9786d9ee990afc659e14a25ce11182b7b69f826407cc1718

build:
  number: 0
  python:
    version_independent: true
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - if: host_platform != build_platform
      then: cross-python_${{ host_platform }}
  host:
    - python-abi3
    - python
    - pip
    - setuptools
  run:
    - python

tests:
  - python:
      imports:
        - spam
  - script:
      - export SP_DIR=$(python -c "import site; print(site.getsitepackages()[0])")
      - abi3audit $SP_DIR/spam.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
    requirements:
      run:
        - abi3audit

about:
  homepage: https://github.com/joerick/python-abi3-package-sample
  summary: 'ABI3 example'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
