# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.0.1"

package:
  name: sourceforge-redirect-test
  version: ${{ version }}

source:
  # This URL requires 3 redirects across different hosts to reach the final file:
  # 1. sourceforge.net -> sourceforge.net/download
  # 2. sourceforge.net/download -> downloads.sourceforge.net?ts=...
  # 3. downloads.sourceforge.net -> [mirror].dl.sourceforge.net
  url: https://sourceforge.net/projects/arma/files/armadillo-15.2.1.tar.xz
  sha256: a5b8109da3c169802f51a14d3bd1246395c24bbca55601760b0c96a3c0b2f8fa

build:
  number: 0
  script:
    - echo "Successfully downloaded from SourceForge with cross-host redirects"
