# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: zlink
  version: ${{ version }}

source:
  path: ../../../examples/linking/zlink/

build:
  script:
    - cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release ${CMAKE_ARGS}
    - cmake --build build --config Release
    - cmake --install build --prefix ${PREFIX}
  dynamic_linking:
    overdepending_behavior: error
    overlinking_behavior: ignore

requirements:
  build:
    - ${{ compiler('c') }}
    - ninja
    - cmake
  host:
    - zlib
  run:
    - yaml

tests:
  - script:
      - zlink
      - ldd $PREFIX/bin/zlink
