package:
  name: test-interpreter-powershell
  version: 0.1.0

build:
  script: build.ps1

requirements:
  build:
    - powershell

tests:
  - script: build.ps1
    requirements:
      run:
        - powershell
