package:
    name: ament_package
    version: "0.14.0"

source:
  git: https://github.com/ros2-gbp/ament_package-release.git
  tag: release/humble/ament_package/0.14.0-4
  target_directory: ros-humble-ament-package/src/work
  patches:
    - patch/ros-humble-ament-package.patch
