# Example: PyPI package with attestation verification
#
# For PyPI sources, the attestation bundle URL is auto-derived from the
# source URL — no need to specify `bundle_url` explicitly. The provenance
# is fetched from https://pypi.org/integrity/{project}/{version}/{filename}/provenance
#
# The `publishers` list specifies which identities must have signed the
# artifact. All listed publishers must match.

context:
  version: "3.1.1"

package:
  name: flask
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/f/flask/flask-${{ version }}.tar.gz
  sha256: 284c7b8f2f58cb737f0cf1c30fd7eaf0ccfcde196099d24ecede3fc2005aa59e
  attestation:
    publishers:
      - github:pallets/foobar

build:
  noarch: python
  script:
    - python -m pip install . -vv

requirements:
  host:
    - pip
    - flit-core <4
    - python 3.10.*
  run:
    - python >=3.9
    - werkzeug >=3.1
    - jinja2 >=3.1.2
    - itsdangerous >=2.2
    - click >=8.1.3
    - blinker >=1.9
    - importlib-metadata >=3.6.0

tests:
  - python:
      imports:
        - flask

about:
  homepage: https://flask.palletsprojects.com/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A lightweight WSGI web application framework
  repository: https://github.com/pallets/flask
