[workspace]
name = "py-rattler-build"
description = "Python bindings for rattler-build"
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
license = "BSD-3-Clause"
preview = ["pixi-build"]
# We are using the oldest supported python version as the build variant here
build-variants = { python = ["3.10"] }

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
compilers = ["rust"]
extra-input-globs = ["../src/**", "../crates/**", "rust/**", "src/**"]
# Use cmake to build aws-lc-sys, because conda's CFLAGS inject -O2 which
# overrides the -O0 required by jitterentropy-base.c, causing a build failure.
env = { AWS_LC_SYS_CMAKE_BUILDER = "1" }

[package.host-dependencies]
python = "*"
maturin = "~=1.12.0"

[package.target.linux.build-dependencies]
patchelf = "~=0.17.2"
cmake = ">=4,<5"
make = ">=4,<5"

[feature.lint.dependencies]
# we need rust for cargo-fmt and clippy
rust = ">=1.96.0,<1.97"
ruff = ">=0.15.18,<0.16"

[feature.lint.tasks]

fmt-rust = "cargo fmt --all --manifest-path rust/Cargo.toml"
# checks for the CI
fmt-rust-check = "cargo fmt --all --check --manifest-path rust/Cargo.toml"

lint-python = "ruff check ."
lint-rust = "cargo clippy --all-targets --workspace --manifest-path rust/Cargo.toml -- -D warnings"

lint = { depends-on = ["lint-python", "lint-rust", "fmt-rust"] }

[feature.test.dependencies]
py-rattler-build = { path = "." }
lua = ">=5.5.0,<6"

# Python 3.10 is the minimum supported version, so we use that for testing
python = ">=3.10.20,<3.11"

ty = ">=0.0.51,<0.0.52"

pytest = ">=9.1.1,<10"
pytest-asyncio = ">=1.4.0,<2"
pytest-xprocess = ">=1.0.2,<2"
inline-snapshot = ">=0.34.2,<0.35"
# used in examples
typer = ">=0.26.7,<0.27"
rich = ">=15.0.0,<16"
zstandard = ">=0.25.0,<0.26"

[feature.test.pypi-dependencies]
types-networkx = ">=3.6.1.20260612, <4"

[feature.test.tasks]
check-cargo-lock = "cargo check --locked --manifest-path rust/Cargo.toml"
test = { cmd = "pytest --durations=0 ./tests", depends-on = ["type-check"] }
type-check = { cmd = "ty check" }

[feature.notebooks.dependencies]
jupyter = ">=1.1.1,<2"


[environments]
default = { features = ["test", "notebooks"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
lint = { features = ["lint"] }

[dependencies]
requests = ">=2.34.2,<3"
sccache = ">=0.16.0,<0.17"
types-requests = ">=2.33.0.20260518,<3"

[activation.env]
RUSTC_WRAPPER = "sccache"
