# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: empty_folder
  version: "0.24.6"

build:
  script:
    - if: win
      then:
        - mkdir %PREFIX%\empty_folder
      else:
        - mkdir -p $PREFIX/empty_folder
