context:
  org: prefix-dev
  name: rattler-build
  version: "0.1.3"

package:
  name: "{{ name }}"
  version: "{{ version }}"


source:
    git_url: "https://github.com/{{ org }}/{{ name }}"
#    git_url: "/home/rarts/development/rattler-build-clean"
#    git_url: "/home/rarts/development/rattler-build-https"
    git_rev: "v{{ version }}"
    git_depth: -1 # (Defaults to -1/not shallow)

build:
  script:
    - cargo-bundle-licenses --format yaml --output ${SRC_DIR}/THIRDPARTY.yml
    - $BUILD_PREFIX/bin/cargo install --locked --bins --root ${PREFIX} --path .

requirements:
  build:
    - "{{ compiler('rust') }}"
    - cargo-bundle-licenses
  host:
    - openssl

test:
  commands:
    - "{{ name }} --help"

about:
  home: "https://github.com/{{ org }}/{{ version }}"
  license: BSD-3-Clause
  description: "rattler-build is a universal package builder for Windows, macOS and Linux"
  about: "rattler-build is a universal package builder for Windows, macOS and Linux"


