context:
  name: spaces-in-paths
  version: 1.0.0

package:
  name: spaces-in-paths
  version: "1.0.0"

build:
  script:
    - if: unix
      then: |
        echo "This is a test with spaces in paths" > "$PREFIX/test.txt"
    - if: win
      then: |
        echo "This is a test with spaces in paths" > "%PREFIX%\test.txt" 
