on:
  push:
    branches: [main]
  workflow_dispatch:

name: Publish Pre-release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    name: Build & Upload (${{ matrix.os }})
    env:
      SCCACHE_GHA_ENABLED: "true"
      ACTIONS_CACHE_SERVICE_V2: on
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
            working-directory: "D:/pixi"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.working-directory || github.workspace }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Copy checkout directory
        run: |
          New-Item ${{ matrix.working-directory }} -ItemType Directory
          Copy-Item D:/a/rattler-build/rattler-build/* ${{ matrix.working-directory }} -Recurse -Force
        working-directory: "D:/"
        if: ${{ matrix.os=='windows-latest' }}
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          environments: packaging
          manifest-path: ${{ matrix.working-directory && format('{0}\pixi.toml', matrix.working-directory) || 'pixi.toml' }}
      - name: Configure sccache
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Build package
        run: pixi run --environment=packaging build-package
        env:
          RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true
      - name: Upload package
        run: pixi run --environment=packaging upload-package
      - name: Show sccache stats
        run: pixi run --environment=packaging sccache --stop-server
