name: "Python Build Validation"

on:
  pull_request:
    paths:
      # When we change pyproject.toml, we want to ensure that the maturin builds still work
      - py-rattler-build/pyproject.toml
      # And when we change this workflow itself...
      - .github/workflows/python-release.yml
      - .github/workflows/python-build.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Python wheels
    uses: ./.github/workflows/python-build.yml
    with:
      sha: ${{ github.sha }}
