name: Python bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change pyproject.toml, we want to ensure that the maturin builds still work
      - test-data/**
      - crates/**
      - Cargo.*

      # When something in the bindings themselves changes
      - "py-rattler-build/**/*"

      # Or when this workflow changes
      - ".github/workflows/python-bindings.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  SCCACHE_GHA_ENABLED: "true"
  ACTIONS_CACHE_SERVICE_V2: on

jobs:
  format_lint_test:
    name: Format, Lint and Test Python bindings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          manifest-path: py-rattler-build/pixi.toml
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Configure sccache
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Check Cargo.lock
        working-directory: py-rattler-build
        run: |
          pixi run check-cargo-lock
      - name: Run tests
        working-directory: py-rattler-build
        run: |
          pixi run test --color=yes
      - name: Show sccache stats
        if: always()
        run: pixi run --manifest-path py-rattler-build/pixi.toml sccache --show-stats
