on:
  # push:
  #   branches: [ main ]
  pull_request:

name: Continuous integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.70.0
      - run: cargo check

  # check-rustdoc-links:
  #   name: Check intra-doc links
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #     - uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: 1.70.0
  #     - run: |
  #         for package in $(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | .name'); do
  #           cargo rustdoc -p "$package" --all-features -- -D warnings -W unreachable-pub
  #         done

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          # fetch all history so that the tests against v0.1.3 work
          fetch-depth: 0
          # The tests require data that is stored in LFS
          lfs: true
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.70.0
      - run: cargo test --all-features -- --nocapture

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt
          toolchain: 1.70.0
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: 1.70.0
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings
