package:
  name: ruby-test
  version: 0.1.0

build:
  number: 0
  script:
    interpreter: ruby
    content: |
      puts "Testing Ruby Interpreter"

      # Create test data and output file
      test_data = [
        { name: "package1", version: "1.0" },
        { name: "package2", version: "2.0" }
      ]

      # Write output to a file
      File.open("#{ENV['PREFIX']}/ruby_test_output.txt", "w") do |file|
        test_data.each do |pkg|
          file.puts "#{pkg[:name]}: #{pkg[:version]}"
        end
      end

      puts "Ruby test completed successfully"

requirements:
  host:
    - ruby

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/ruby_test_output.txt
          - grep "package1: 1.0" $PREFIX/ruby_test_output.txt
          - grep "package2: 2.0" $PREFIX/ruby_test_output.txt
      - if: win
        then:
          - if not exist %PREFIX%\ruby_test_output.txt exit 1
          - findstr "package1: 1.0" %PREFIX%\ruby_test_output.txt
          - findstr "package2: 2.0" %PREFIX%\ruby_test_output.txt

about:
  summary: Test package for Ruby interpreter support
  license: MIT
